#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="makeTriSurfaceMesh"

runApplication blockMesh

runApplication $application

if [ ! -d "../cavity/constant/triSurface" ] ; then
    mkdir ../cavity/constant/triSurface
fi

cp ibCylinder.* ../cavity/constant/triSurface
