#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

compileApplication refineCylinderMesh

rm -rf 0

runApplication blockMesh
cp -f boundary constant/polyMesh/boundary

runApplication refineCylinderMesh -overwrite

runApplication refineImmersedBoundaryMesh -overwrite
rm log.refineImmersedBoundaryMesh

runApplication refineImmersedBoundaryMesh -overwrite

cp -r 0.orig 0

#runApplication potentialIbFoam
runApplication $application
